# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c306831e2056792902c8a392545d8c57fc45dcda1ad8f12c7b3e15f4b4a29899996932002740730487f9cbd5b6d033ab07bbb2aeadd2be147921b0777d96061c

test:
  secret_key_base: 839f4d8d22adf2dbe8dc34ab5435c1b5788ce6f37c484feaf465a7ed7d2a1682cbfa4ea88e718010cae8000a0f2a858b777d89d7be0b72bb51b55d79fc0f179b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
